inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/migrate/**.rb'
    - 'db/**.rb'
    - 'config/initializers/**'
    - 'config/environments/**'
    - 'config/**'
    - 'vendor/bundle/ruby/2.5.0/gems/**'
